# Generated by Django 4.2.6 on 2023-11-15 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_alter_task_attached'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='attached',
            field=models.FileField(blank=True, null=True, upload_to='main/task_submissions/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='grading_attached',
            field=models.FileField(blank=True, null=True, upload_to='main/task_grading/%Y%m%d'),
        ),
        migrations.CreateModel(
            name='SubmissionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Posted')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified')),
                ('content', models.TextField(blank=True, max_length=5000)),
                ('visible', models.BooleanField(blank=True, default=True, null=True)),
                ('attached', models.FileField(blank=True, null=True, upload_to='main/task_comments/%Y%m%d')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_comments', to='main.tasksubmission')),
            ],
        ),
    ]
